#-------------------------------
# General Site Settings

title: Satyajit Ghosh
logo: logo.png
email: satyajitghosh1111@gmail.com
phone: +91 8447520696

menu:
- {name: Resume, link: 'drive.google.com/file/d/1J6ug-hjsRgoqPgpxJHHMNu-f8sjjZCKX/view?usp=sharing'}
# - {name: Blog, link: '/blog'}
- {name: Kaggle, link: 'https://www.kaggle.com/saty101'}
- {name: Github, link: 'https://github.com/saty101'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Satyajit Ghosh

social:

#- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Hello, I'm Satyajit, a 3rd year student at BITS Pilani pursuing M.Sc.Physics and B.E. Electronics and Instrumentation. I have a keen interest in Deep Learning on publicly available data and building things. I am currently looking for opportunites to apply my learning to practical scenarios and gain a wider, more holisitic understanding of various fields.

#blurb-btn-link: '/about'
#blurb-btn-name: know more


# About Page

# Work Process Section
# work-process:
#   - title : "Research and Plan"
#     icon : "assets/images/icons/plan.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Design and Develop"
#     icon : "assets/images/icons/design.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Deliver"
#     icon : "assets/images/icons/print.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# # My Team Section
# team:
#   - title : "Jack Schenziwe"
#     image : "assets/images/team/member-1.png"
#     designation : "Project Manager"
    
#   - title : "Julias Carlie"
#     image : "assets/images/team/member-2.png"
#     designation : "Web Developer"
    
#   - title : "John Doe"
#     image : "assets/images/team/member-3.png"
#     designation : "Designer"


#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Machine Learning Summer Intern, icon: 'icon-1.png', date: 'May 2020 - June 2020', organization: 'Industry ARC, Hyderabad'}
# - {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: M.Sc. in Physics, date: '2018-2023', organization: 'BITS Pilani, Pilani Campus'}
- {name: B.E. Electronics & Instrumentation, date: '2018-2023', organization: 'BITS Pilani, Pilani Campus'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

# services-title: Services
# services:
# - {
#     name: UI Design,
#     icon: ti-palette,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }
# - {
#     name: UX Design,
#     icon: ti-vector,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: true # Add true to select section
#   }
# - {
#     name: Interaction Design,
#     icon: ti-panel,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items: 
  - image : "assets/images/portfolio/image-captioning.png"
    url: "https://github.com/saty101/Image-Captioning"
    name: Image Caption Generator
    
  - image : "assets/images/portfolio/captcha-recognizer.png"
    url: "https://github.com/saty101/Captcha-Text-Recognition"
    name: Captcha Text Recognition
    
  - image : "assets/images/portfolio/lapsrn.png"
    url: "https://saty101.github.io/blog_site/2020/07/28/Lapsrn4x.html"
    name: Super-Resolution
    
#   - image : "assets/images/portfolio/item-4.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"


# Portfolio Page
# portfolio-label:
# - {
#     title : "UI/UX Design",
#     type : "design"
#   }
# - {
#     title : "BRANDING",
#     type : "branding"
#   }
# - {
#     title : "ILLUSTRATION",
#     type : "illustration"
#   }

# portfolio-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#      - type: "design"
#      - type: "illustration"
      
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
      
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: satyajitghosh1111@gmail.com
